### ISSUE TITLE
Learn command throwing file load errors (even on sol'n branch) - Lab may have setup issue

### ISSUE THREAD

**Issue by JessRudder** [learn-co-curriculum/oo-student-scraper#10]
I did a fresh fork, clone and bundle install of this lab and I got the following error message (similar to what a student was seeing):

```
/Users/jessica/code/oo-student-scraper-v-000/config.rb:1:in `require': cannot load such file -- vcr (LoadError)
	from /Users/jessica/code/oo-student-scraper-v-000/config.rb:1:in `<top (required)>'
	from /Users/jessica/code/oo-student-scraper-v-000/spec/spec_helper.rb:3:in `require_relative'
	from /Users/jessica/code/oo-student-scraper-v-000/spec/spec_helper.rb:3:in `<top (required)>'
	from /Users/jessica/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `require'
	from /Users/jessica/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `block in requires='
	from /Users/jessica/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `each'
	from /Users/jessica/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `requires='
	from /Users/jessica/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:103:in `block in process_options_into'
	from /Users/jessica/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:102:in `each'
	from /Users/jessica/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:102:in `process_options_into'
	from /Users/jessica/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:22:in `configure'
	from /Users/jessica/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:95:in `setup'
	from /Users/jessica/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84:in `run'
	from /Users/jessica/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
	from /Users/jessica/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
	from /Users/jessica/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/exe/rspec:4:in `<top (required)>'
	from /Users/jessica/.rvm/gems/ruby-2.1.2/bin/rspec:23:in `load'
	from /Users/jessica/.rvm/gems/ruby-2.1.2/bin/rspec:23:in `<main>'
	from /Users/jessica/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jessica/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
/Users/jessica/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/fileutils.rb:1454:in `unlink': No such file or directory @ unlink_internal - .results.json (Errno::ENOENT)
	from /Users/jessica/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/fileutils.rb:1454:in `block in remove_file'
	from /Users/jessica/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/fileutils.rb:1459:in `platform_support'
	from /Users/jessica/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/fileutils.rb:1453:in `remove_file'
	from /Users/jessica/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/fileutils.rb:791:in `remove_file'
	from /Users/jessica/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/fileutils.rb:569:in `block in rm'
	from /Users/jessica/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/fileutils.rb:568:in `each'
	from /Users/jessica/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/fileutils.rb:568:in `rm'
	from /Users/jessica/.rvm/gems/ruby-2.1.2/gems/learn-test-1.2.23/lib/learn_test/rspec/runner.rb:118:in `cleanup'
	from /Users/jessica/.rvm/gems/ruby-2.1.2/gems/learn-test-1.2.23/lib/learn_test/rspec/runner.rb:28:in `run'
	from /Users/jessica/.rvm/gems/ruby-2.1.2/gems/learn-test-1.2.23/bin/learn-test:71:in `<top (required)>'
	from /Users/jessica/.rvm/gems/ruby-2.1.2/bin/learn-test:23:in `load'
	from /Users/jessica/.rvm/gems/ruby-2.1.2/bin/learn-test:23:in `<main>'
	from /Users/jessica/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jessica/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

I checked out the solution branch, did a bundle install and ran learn and got the same error.

cc @abhishekpillai - this is related to the issue you were troubleshooting with DianeCai

**Comment by deniznida** [comment]
@JessRudder hey, @ipc103 and I got the same error first but after running bundle we both could run learn. Our machines are using ruby 2.2.3. The learn gem requires at least 2.2.0 right?

**Comment by JessRudder** [comment]
@deniznida 

Interesting.  I checked and my Ruby version on this lab was set to 2.1.2.  I changed it to 2.2.3 and got the following:

```bash
♥ learn
Could not find proper version of rspec-core (3.1.7) in any of the sources
Run `bundle install` to install missing gems.
[10:18:24] (solution) oo-student-scraper-v-000

♥ bundle install
Using addressable 2.4.0
Using coderay 1.1.0
Using safe_yaml 1.0.4
Using crack 0.4.3
Using hashdiff 0.2.3
Using method_source 0.8.2
Using mini_portile2 2.0.0
Using nokogiri 1.6.7.1
Using slop 3.6.0
Using pry 0.10.3
Using vcr 3.0.1
Using webmock 1.22.6
Using bundler 1.10.6
Bundle complete! 4 Gemfile dependencies, 13 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

♥ learn
Could not find proper version of rspec-core (3.1.7) in any of the sources
Run `bundle install` to install missing gems.
```

At that point, adding 'rspec' into the gem file and rebundling resolved it.

Not sure if rspec should be in the gemfile from the start or if it's only needed due to some other environment issue I'm having.

If it is a case-by-case environment-caused issue, feel free to close (and thanks for looking into it!).
